# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: U.S. Indicators For The Sustainable Development Goals
description: Data Platform Prototype
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
data_dir: data
environment: production
remotedatabaseurl: "https://brock-code.github.io/sdg-data"
# permalink: /news/:year/:month/:day/:title.html

jekyll_get_data:
  - data: meta
    json: 'https://brock-code.github.io/sdg-data/meta/all.json'
    # cache: true
    # directory: 'remotedata'
  - data: headlines
    json: 'https://brock-code.github.io/sdg-data/headline/all.json'
    # cache: true
    # directory: 'remotedata'
  - data: schema
    json: 'https://brock-code.github.io/sdg-data/meta/schema.json'
  - data: translations
    json: 'http://brock.tips/sdg-translations/translations.json'

analytics:
  ga_prod: ''

###################################################################################################
email_contacts:
  questions: FN-OMB-OIRA-SDGs@omb.eop.gov
  suggestions: FN-OMB-OIRA-SDGs@omb.eop.gov
  functional: datagov@gsa.gov
###################################################################################################

# Github Repo for Data
repo_name: sdg-data
branch: develop
org_name: brockfanning

# Build settings
markdown: kramdown

# Travis Support
exclude: [vendor, scripts, remotedata]

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: US
  adjective: US

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Menu
menu:
  - path: /reporting-status
    translation_key: reporting_status
  - path: /about
    translation_key: about
  - path: /guidance
    translation_key: guidance
  - path: /faq
    translation_key: faq

# The list of languages that are translated. The first one is the default.
languages:
  - en
  - es
  - fr

# This makes sure that all pages have a language.
defaults:
  -
    scope:
      path: ""
    values:
      language: "en"

plugins:
  - jekyll-remote-theme

remote_theme: brockfanning/sdg-theme@multilingual

custom_css:
  - /assets/css/custom.css
