# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build_prod:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: test-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - save_cache:
          key: test-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Build the Jekyll site
          command: bundle exec jekyll build --config _config_prod.yml
      - persist_to_workspace:
          root: ~/repo
          paths:
            - _site
  deploy_prod:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/build
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync --acl public-read --sse --delete /tmp/build/_site s3://www.my-sdg-nrp.org
  build_staging:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: test-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - save_cache:
          key: test-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Build the Jekyll site
          command: bundle exec jekyll build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - _site
  deploy_staging:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/build
      - add_ssh_keys:
          fingerprints:
            # Replace this with the fingerprint for gh-stg.
            - "31:d1:7d:9e:b4:78:3d:c0:ac:66:71:03:11:02:47:0c"
      - run:
          name: Deploy to Github
          command: bash scripts/deploy/circleci/deploy_staging.sh
workflows:
  version: 2
  deploy:
    jobs:
      - build_prod:
          filters:
            branches:
              only: master
      - deploy_prod:
          requires:
            - build_prod
          filters:
            branches:
              only: master
      - build_staging:
          filters:
            branches:
              only: develop
      - deploy_staging:
          requires:
            - build_staging
          filters:
            branches:
              only: develop
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: develop
    jobs:
      - build_staging
      - deploy_staging
