# Python CircleCI 2.0 configuration file
version: 2
jobs:
  deploy:
    # The build job does compile the Jekyll site, so Ruby is needed.
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Any additional provisioning.
          command: bash scripts/provision/provision.circleci.sh
      - restore_cache:
          key: test-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - run:
          name: Install front-end libraries.
          command: npm install
      - save_cache:
          key: test-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "package-lock.json" }}
          paths:
            - vendor/bundle
      - run:
          name: Build the Jekyll site
          command: bundle exec jekyll build
      - add_ssh_keys:
          fingerprints:
            - "06:60:53:ac:f3:70:f6:fe:3c:02:42:9f:7f:bf:24:40"
      - run:
          name: Deploy to Github
          command: bash scripts/deploy/deploy_staging.circleci.sh
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: develop
