# Python CircleCI 2.0 configuration file
version: 2
jobs:
  deploy_prod:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: test-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - save_cache:
          key: test-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Build the Jekyll site
          command: bundle exec jekyll build --config _config_prod.yml
      - add_ssh_keys:
          fingerprints:
            - "06:60:53:ac:f3:70:f6:fe:3c:02:42:9f:7f:bf:24:40"
      - run:
          name: Deploy to Github
          command: bash scripts/deploy/deploy.circleci.sh
  deploy_staging:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: test-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - save_cache:
          key: test-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Build the Jekyll site
          command: bundle exec jekyll build
      - add_ssh_keys:
          fingerprints:
            - "06:60:53:ac:f3:70:f6:fe:3c:02:42:9f:7f:bf:24:40"
      - run:
          name: Deploy to Github
          command: bash scripts/deploy/deploy_staging.circleci.sh
workflows:
  version: 2
  deploy:
    jobs:
      - deploy_prod:
          filters:
            branches:
              only: master
      - deploy_staging:
          filters:
            branches:
              only: develop
